apiVersion: cert-manager.io/v1
kind: Certificate
metadata:
  name: chibi-moe-tls
  namespace: k8sdemo
spec:
  secretName: chibi-moe-tls
  duration: 2160h   # 90 days
  renewBefore: 360h # 15 days before expiry
  dnsNames:
    - chibi.carrot-atelier.online
  issuerRef:
    name: letsencrypt-prod
    kind: ClusterIssuer
