apiVersion: apps/v1
kind: Deployment
metadata:
  name: chibi-moe-server
  namespace: k8sdemo
spec:
  replicas: 1
  selector:
    matchLabels:
      app: chibi-moe-server
  template:
    metadata:
      labels:
        app: chibi-moe-server
        env: production
        managed-by: argocd
      annotations:
        deployed-at: "2026-07-20 03:18:36"
    spec:
      imagePullSecrets:
        - name: ocirsecret
      containers:
      - name: server
        image: ghcr.io/darkschneider1024/chibi-moe-server:8e197faa5c330b53513da326dde9d724ae99e07a
        imagePullPolicy: Always
        ports:
        - containerPort: 3001
        resources:
          requests:
            memory: "128Mi"
            cpu: "50m"
          limits:
            memory: "256Mi"
            cpu: "200m"
